### ISSUE TITLE
Outline our basic development process

### ISSUE THREAD

**Issue by escowles** [pulibrary/drds-handbook-deprecated#1]
Add a Markdown file that outlines our current development process

**Comment by sdellis** [comment]
I think this seems like a good opportunity to note any perceived gaps and shortcomings in that process, with hopes of addressing them in the near future.

**Comment by escowles** [comment]
@sdellis Yes, exactly.  I've asked Christina, as the newest addition to our group, to do this initial description to help check for differences between our actual practice and how oldtimers think of it.  It might be an interesting exercise if you or others wanted to also describe our process separately to see how they compare.

**Comment by christinach** [comment]
a 1st description was provided by https://github.com/pulibrary/app_team_handbook/pull/11

**Comment by hackartisan** [comment]
This is done; see development_practice.md
