### ISSUE TITLE
Document product owner role

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/drds-handbook-deprecated#19]
Write up what it means to be a PO for one of our applications. In the process I expect we'll want to talk about what we need / expect / wish for from POs.

**Comment by hackartisan** [comment]
* How much do we want (want to ask) POs to participate in sprint planning / standups / wrapup? They may expect a more traditional meeting calendar (like "once a month" as opposed to "daily or twice a week whenever we're working on your product")
* What github is and how we use it.
  * Do we expect POs to have github accounts?
    * If so a list of POs and their github ids would be really helpful, perhaps along with a tech lead list.
* POs need to know some context about the cadance of our team's work cycles. They may not really know the difference between our team and EUS.
* Expectations for how communication happens, and reasons why.

**Comment by escowles** [comment]
I think it might be good to approach this from the perspective of what we need day-to-day, vs. what would be nice to have, vs. what we might expect at crunch times (e.g., week before production deploy).  Something like:

* All the time:
   * Available to answer questions on Slack or email
   * Attend demos approx. every 2 weeks
* Nice to have:
   * Attend weekly meeting on Monday or Friday
* Crunch time:
   * Attend daily standup
