### ISSUE TITLE
Migrate "DRDS tools" google doc to this repo

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/drds-handbook-deprecated#29]
I propose that the doc be migrated into the following pages in this handbook:
 - development_practice (also the current dev_process.md) will be moved here
 - tooling
 - administrative_info
 - drds_overview (including the "communication" section of the doc)
 - some info will go into the "applications" page

**Comment by escowles** [comment]
The current Google Doc is in the ITIMS team drive: https://docs.google.com/document/d/1QCB0A4YV8-9Zar71ocYEA62zY_4LxWRAleDBi3AIIgw/edit
