### ISSUE TITLE
Outline the development environment tools used on our team

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/drds-handbook-deprecated#38]
During an onboarding session, it became necessary to discuss and describe the common, recommended usage of https://github.com/thoughtbot/dotfiles, https://github.com/thoughtbot/rcm, https://ohmyz.sh/, tmux, as well as iTerm2. While these are not consistently used at all by all team members, perhaps some general outline of their effective usage might be helpful.

--- 
We'll create a page listing development tools used by the team. Everyone list your tools here and I (@hackartisan) can compile them into a PR. This is intended to provide guidance to anyone who doesn't already have a go-to tool of a certain type or is looking for new options for a tool they are no longer happy with.

Tools to provide: editor, language version manager/s, shell, dotfiles management, terminal session management

**Comment by jrgriffiniii** [comment]
Also, (and perhaps this is another issue), perhaps some documentation outlining the preferred usage of `asdf`, `chruby`, and `RVM` should be provided for managing different versions of Ruby (as well as for managing different versions of `bundler`).

**Comment by tpendragon** [comment]
Tools I Use:
* zsh
* tmux
* rcm
* dotfiles
* asdf for ruby/python/etc.
* vim
* lando

**Comment by christinach** [comment]
Tools I use:

- VS code

- Textmate

- nvm (nodejs)

- rvm (ruby, rails)

- pyenv (python)

- snagit

- tmux

- postman

**Comment by cwulfman** [comment]
I suspect no one will much care what I use, but here's a partial list anyway:

- emacs
- Oxygen
- tmux
- zsh
- pyscaffold
