### ISSUE TITLE
Process for closing issues?

### ISSUE THREAD

**Issue by kmcelwee** [pulibrary/drds-handbook-deprecated#45]
I was unsure if this is solely for the tech lead to handle. If the PR was accepted, is it always safe to close? Is there any confirmation process before closing an issue?

**Comment by hackartisan** [comment]
Generally yes we close the issues via keywords in PRs. We have messed around with things like a "demo" column where issues stay open until work is approved by stakeholders. But I'm not sure that really panned out.

Do you have a sense of where this documentation should be? Feel free to add it and post a PR if so!
