### ISSUE TITLE
Add a glossary

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/drds-handbook-deprecated#48]
There may be a library-wide one we can use

Otherwise, need to lookup acronyms used in this department.

A list we can add to:
- PRDS: Princeton Research Data Service, part of the Office of Research Data and Open Scholarship
- There are a lot of projects we might add here, e.g. "Geniza"
- DPSG / DPOG: Digital Projects Steering group, changing to Digital Projects Operations Group. This group vets and approved new digitization projects, which are a primary source of new feature requests for Figgy and DPUL.
- ReCAP: [The Research Collections and Preservation  Consortium](https://recap.princeton.edu/) ReCAP refers to both the consortium and its offsite storage location that stores materials from Princeton, NYPL, and Columbia (and soon Harvard)
- SCSB: Shared Collection Service Bus, pronounced "scuzzy-B", middleware used by ReCAP to integrate their inventory system with our ILS / bibdata
- LAS: The ReCAP inventory system
- HTC: The contract company that develops ReCAP's inventory system
- CDL: controlled digital lending. An orangelight / figgy feature and also a white paper
- OIT: Office of Information Technology, the university's central IT department
- SN@P: Service Now at Princeton, the issue tracker and knowledge base management system used by OIT and by the library operations team.
- OARSC: Open Access to Restricted Special Collections - this is the functionality provided by figgy that allows us to make restricted items available digitally to specific people. Related to the "Virtual Reading Room" project
- POD: platform for open discovery. A "data lake" of marc data from all 13 Ivies+ institutions

**Comment by hackartisan** [comment]
Here's a list of committees: https://pulstaff.princeton.edu/pul-committees/

Here's the Acronym list I saw a while back; doesn't look super maintained so I'm not sure if something more formal has replaced it: https://docs.google.com/document/d/1kkchnUR4fbEE9kE0UTXntaZPxK7hlhgmuHD3cCwa5dw/edit (update: this has since been deleted)

**Comment by kelea99** [comment]
Looking at both links, some of the items on the acronym list are not accurate (and some are outdated).

**Comment by hackartisan** [comment]
The current acronym list for new hires is https://docs.google.com/spreadsheets/d/1tlkkIkTDdlcaqztnH8jVaQ_RjXS6KetQVEa8yxccWUI/edit?ts=5fdf9f27#gid=1045672532 (update: this has since been deleted)
