### ISSUE TITLE
remove "guests first" policy on daily checkins

### ISSUE THREAD

**Issue by kayiwa** [pulibrary/drds-handbook-deprecated#57]
Yes that's deliberately inflammatory (my apologies). Or certainly re-label that to be more inclusive. The unintended side effects of this new policy is (sample of one)

- it discourages collaboration in suggesting that I should care about only the tiny part where I intersect with your team
- it discourages "guests"  to just come in and "just listen" (wearing my devops hat)

Spending time listening to what other colleagues are doing cannot ever be considered a waste of time. Yes, we are all busy.

**Comment by hackartisan** [comment]
The documentation refers to "Non-DRDS attendees" and I am also wondering if it would be more inclusive to say "cross-team attendees"

@kayiwa do you think this policy should also be removed for Mondays and/or Fridays?

**Comment by tpendragon** [comment]
@kayiwa Is it wording and a set of practices, do you think folks should be mixed in and randomly called on, or do you want to return to going last as before? Like can we just change the "guests" wording and not add a note there saying folks can leave, in case it gives the impression that we want you to leave (which we definitely don't!) I think what we were worried about is we just don't schedule these meetings with other teams' schedules in mind, so we worry that we're blocking commitments. Or I do, at least.

**Comment by sdellis** [comment]
@kayiwa I agree that it's always great to "just listen", but other tasks/projects may be prioritized by our supervisors. Giving cross-team guests an accurate window of time during which they can update the team is the most respectful approach. 

I do not think this discourages folks from sticking around to hear about what the rest of the team is working on. I often stick around after I have had my turn to talk.

Some guests (like myself) have their own check-ins that they attend as well, even when they are working on cross-team projects. It also makes me wonder if we are discouraging collaboration in our User Services check-ins as we rarely have any guests or people dropping in to just listen. Is this something we need to be more aware of encouraging? Do folks feel excluded?

**Comment by hackartisan** [comment]
@sdellis do you think the new drds practice of shortening the daily (tue-thu) checkin to 15 minutes sufficiently addresses your concerns? Or the cross-team attendees going first is still important?

**Comment by hackartisan** [comment]
closed by #59
