### ISSUE TITLE
Two-week sprints?

### ISSUE THREAD

**Issue by escowles** [pulibrary/drds-handbook-deprecated#7]
To reduce context-switching, would we rather book two-week sprints instead of one-week sprints?

**Comment by tpendragon** [comment]
I like one week sprints, but I also don't think we do them - no retros or planning at the beginning really. If two week sprints make that happen then :+1:.

**Comment by hackartisan** [comment]
We're still sort of in a hybrid space. I think describing our approach as "work cycles" rather than "sprints" makes sense. Regardless, this seems like the sort of thing our team will talk about during our periodic team retros as opposed to in an issue.
